Fixed large variants in variant_key and added documentation and a test.
monarch-initiative/genophenocorr pull request #204
Opened 2024-08-07 15:26 UTC by lnrekerle

Closes #183 

Made a small change that printed the alt/ref that is not long rather than "None" which was a bug from the last PR that changed variant_key. 
I also added a line of documentation describing that what happens if "ref" or "alt" are over 50 base pairs. And I added a test that makes sure it prints correctly.

2024-08-07 15:38 UTC, lnrekerle commented
@pnrobinson @ielis 
I don't know where this error is coming from - "ERROR tests/analysis/test_mtc_filter.py::TestHeuristicSamplerMtcFilter::test_filter_terms_to_test - ValueError: The CURIE 0025354 has no colon `:` or underscore `_`"
It appears to be happening during the creation of the fixture mtc_filter, could it be a bug in the hpo file?

2024-08-07 16:16 UTC, pnrobinson commented
@lnrekerle On my machine, this test is passed. Unlcear what the issue is, as I could not find an instance of that id without the prefix

2024-08-07 16:17 UTC, pnrobinson submitted a review, later dismissed
If we can figure out the error, this looks mergable!

2024-08-12 18:40 UTC, ielis commented on src/genophenocorr/model/_variant.py
> +        If the 'ref' or 'alt' sequences are over 50 bases, they are replaced with the number of bases. Example: ``16_78386858_78425054_--38197bp--_A``
The code of this function not doing what is advertised.
In other words, the pydoc suggests some behavior, but the code does something else.

2024-08-12 19:03 UTC, ielis requested changes
Please fix either the documentation or the code to make sure the code does what the documentation suggests.

Also, please add tests that will cover all branches of the `variant_key` function. Please find the best place for the tests (within the `tests` folder).

2024-08-15 13:21 UTC, ielis requested changes
The tests are now the only thing missing. Please see the comment below for more info.

I made a `TestVariantCoordinates` test suite with one test so far. The test includes one test for a SNP. Please add more tests so that we can be sure that the method you implemented works in the expected fashion.

Thank you!

2024-08-15 13:21 UTC, ielis commented on tests/model/test_variant.py
> +        ] # Couldn't find an example that produces a variant key similar to this: 22_10001_20000_INV
We probably do not have such variant in *SUOX*. However, it is not too hard to create a `VariantCoordinates` instance that is OK for testing.

Please see `TestVariantCoordinates::test_variant_key` test function and add tests for the other cases.

2024-08-20 09:45 UTC, ielis approved these changes
Awesome, thanks!

2024-08-20 09:47 UTC, merged