Reporting the number of tests in GenotypePhenotypeAnalysisResult
monarch-initiative/genophenocorr pull request #209
Opened 2024-08-12 17:38 UTC by lnrekerle

This will close #98 

Added a property to GenotypePhenotypeAnalysisResult called total_tests and it reports the total number of phenotype tests that were run for that analysis.

2024-08-12 18:03 UTC, pnrobinson submitted a review, later dismissed

2024-08-12 18:04 UTC, pnrobinson commented
@lnrekerle please clean up the CI: AttributeError: 'GpCohortAnalysis' object has no attribute 'compare_by_recessive_variant_effect'

2024-08-12 19:11 UTC, ielis requested changes
Looks good except for the one issue below (also pointed out by Peter).

2024-08-12 19:11 UTC, ielis commented on src/genophenocorr/analysis/_gp_impl.py
I concur on the need of removing this at some point soon, but it isn't 100% necessary to do it in this PR, unless you take the time to remove the usages across the entire code base (+notebooks).

Pls either revert the methods or remove all usages.

2024-08-14 11:33 UTC, ielis approved these changes
Looks great, thank you!

2024-08-14 15:34 UTC, merged